--- 
- hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    bucketname: udittestbucket
  tasks: 
    - 
      name: "Create S3 bucket"
      s3: 
        bucket: "{{ bucketname }}"
        mode: create
